version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "crypto_db_local"
      POSTGRES_USER: "crypto_user"
      POSTGRES_PASSWORD: "crypto_pass"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"