spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_db_local
    username: crypto_user
    password: crypto_pass
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop
currency:
  ids: 90,80,48543